import { TermsAndPrivacy } from "./TermAndPrivacy";

export const registerFormData = {
    fields: [
        {
            id: "firstName",
            type: "text",
            placeholder: "",
            required: true,
            autoComplete: "given-name",
            label: "Prénom",
            onChange: () => {},
        },
        {
            id: "lastName",
            type: "text",
            placeholder: "",
            required: true,
            autoComplete: "family-name",
            label: "Nom de famille",
            onChange: () => {},
        },
        {
            id: "address",
            type: "text",
            placeholder: "",
            required: true,
            autoComplete: "street-address",
            label: "Adresse",
            onChange: () => {},
        },
        {
            id: "city",
            type: "text",
            placeholder: "",
            required: true,
            autoComplete: "address-level2",
            label: "Ville",
            onChange: () => {},
        },
        {
            id: "postalCode",
            type: "text",
            placeholder: "",
            required: true,
            autoComplete: "postal-code",
            label: "Code postal",
            onChange: () => {},
        },
        {
            id: "country",
            type: "text",
            placeholder: "",
            required: true,
            autoComplete: "country-name",
            label: "Pays",
            onChange: () => {},
        },
        {
            id: "email",
            type: "email",
            placeholder: "",
            required: true,
            autoComplete: "email",
            label: "Adresse e-mail",
            onChange: () => {},
        },
        {
            id: "phone",
            type: "tel",
            placeholder: "",
            required: true,
            autoComplete: "tel",
            label: "Numéro de téléphone",
            onChange: () => {},
        },
        {
            id: "password",
            type: "password",
            placeholder: "",
            required: true,
            autoComplete: "current-password",
            label: "Mot de passe",
            onChange: () => {},
        },
        {
            id: "confirmPassword",
            type: "password",
            placeholder: "",
            required: true,
            autoComplete: "new-password",
            label: "Confirmer le mot de passe",
            onChange: () => {},
        },
        {
            id: "terms",
            type: "checkbox",
            placeholder: "",
            required: true,
            autoComplete: "",
            label: TermsAndPrivacy,
            onChange: () => {},
        }
    ],
    buttonContent: "S'inscrire",
    onSubmit: () => {},
    title: "Créer un compte"
}