import { IFormProps } from "@organisms/Form/Form.props";
import { FormSubmitResult } from "../../../types/FormSubmitResult";

export const addVehicleFormData: IFormProps = {
    title: "Ajouter un véhicule",
    type: "addVehicle",
    fields: [
        {
            kind: "base",
            id: "categoryId",
            type: "select",
            required: true,
            label: "ID de catégorie",
            placeholder: "",
            options: ["1", "2"].map((opt) => ({
                label: opt,
                value: opt,
            })),
            onChange: () => {},
        },
        {
            kind: "base",
            id: "brand",
            type: "text",
            required: true,
            label: "Marque",
            placeholder: "Ex: Fiat",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "model",
            type: "text",
            required: true,
            label: "Modèle",
            placeholder: "Ex: Ducato",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "mileage",
            type: "number",
            required: true,
            label: "Kilométrage",
            placeholder: "Ex: 50000",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "registrationDate",
            type: "date",
            required: true,
            label: "Date d'immatriculation",
            placeholder: "",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "registrationPlate",
            type: "text",
            required: true,
            label: "Plaque d'immatriculation",
            placeholder: "Ex: AB123CD",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "description",
            type: "textarea",
            required: false,
            label: "Description",
            placeholder: "Description du véhicule",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "numberOfSeats",
            type: "number",
            required: true,
            label: "Nombre de sièges",
            placeholder: "Ex: 4",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "numberOfSleepingPlaces",
            type: "number",
            required: true,
            label: "Places pour dormir",
            placeholder: "Ex: 2",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "length",
            type: "number",
            required: true,
            label: "Longueur (m)",
            placeholder: "Ex: 6.5",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "height",
            type: "number",
            required: true,
            label: "Hauteur (m)",
            placeholder: "Ex: 2.8",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "weight",
            type: "number",
            required: true,
            label: "Poids (kg)",
            placeholder: "Ex: 3500",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "fuelType",
            type: "select",
            required: true,
            label: "Type de carburant",
            placeholder: "",
            options: ["diesel", "petrol", "electric", "hybrid", "other"].map((
                opt,
            ) => ({
                label: opt,
                value: opt,
            })),
            onChange: () => {},
        },
        {
            kind: "base",
            id: "gearType",
            type: "select",
            required: true,
            label: "Type de transmission",
            placeholder: "",
            options: ["manual", "automatic"].map((
                opt,
            ) => ({
                label: opt,
                value: opt,
            })),
            onChange: () => {},
        },
        {
            kind: "base",
            id: "consumption",
            type: "number",
            required: true,
            label: "Consommation (L/100km)",
            placeholder: "Ex: 8.5",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "cityName",
            type: "text",
            required: true,
            label: "Ville",
            placeholder: "Ex: Lyon",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "latCoordinates",
            type: "text",
            required: true,
            label: "Latitude",
            placeholder: "Ex: 45.7640",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "lonCoordinates",
            type: "text",
            required: true,
            label: "Longitude",
            placeholder: "Ex: 4.8357",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "insuranceNumber",
            type: "text",
            required: true,
            label: "Numéro d'assurance",
            placeholder: "Ex: 123456789",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "insuranceExpirationDate",
            type: "date",
            required: true,
            label: "Expiration de l'assurance",
            placeholder: "",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "basePrice",
            type: "number",
            required: true,
            label: "Prix journalier (€)",
            placeholder: "Ex: 75",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "isAvailable",
            type: "checkbox",
            required: false,
            label: "Disponible à la location",
            placeholder: "",
            onChange: () => {},
        },
        {
            kind: "base",
            id: "equipmentIds",
            type: "text",
            required: false,
            label: "IDs des équipements (séparés par des virgules)",
            placeholder: "uuid1,uuid2,...",
            onChange: () => {},
        },
    ],
    buttonContent: "Enregistrer",
    onSubmit: async (
        formData: { [key: string]: string | File | boolean | string[] },
    ): Promise<FormSubmitResult> => {
        console.log("Données du formulaire véhicule :", formData);
        return { ok: true, errors: {} };
    },
};
