<section class="intro">
    <form class="search-form">
        <div class="toggle-switch">
        <input type="radio" id="camping-car" name="vehicle-type" value="camping-car" checked>
        <label for="camping-car">Camping-car</label>
        <input type="radio" id="van" name="vehicle-type" value="van">
        <label for="van">Van</label>
        </div>
        <input type="text" placeholder="Lieu de départ">
        <input type="date" placeholder="Date de départ">
        <input type="date" placeholder="Date de retour">
        <button type="submit">Rechercher</button>
    </form>
</section>