export type VehicleRegisterPayload = {
	categoryId: string;
	brand: string;
	model: string;
	mileage: string;
	registrationDate: string;
	registrationPlate: string;
	description: string;
	numberOfSeats: string;
	numberOfSleepingPlaces: string;
	length: string;
	height: string;
	weight: string;
	fuelType: "diesel" | "petrol" | "electric" | "hybrid" | "other";
	gearType: "manual" | "automatic";
	consumption: string;
	cityName: string;
	cityCode: string;
	insuranceNumber: string;
	insuranceExpirationDate: string;
	basePrice: string;
	isAvailable?: boolean;
	equipmentIds: string[];
	pictures: string[];
};

export type VehicleUpdatePayload = {
	categoryId: string;
	brand: string;
	model: string;
	mileage: string;
	registrationDate: string;
	registrationPlate: string;
	description: string;
	numberOfSeats: string;
	numberOfSleepingPlaces: string;
	length: string;
	height: string;
	weight: string;
	fuelType: "diesel" | "petrol" | "electric" | "hybrid" | "other";
	gearType: "manual" | "automatic";
	consumption: string;
	cityName: string;
	cityCode: string;
	insuranceNumber: string;
	insuranceExpirationDate: string;
	basePrice: string;
	isAvailable?: boolean;
	equipmentIds?: string[];
};
